"""
Django settings for inventrix project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'change-this-in-production-use-env-file')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Los JWT se firman con SECRET_KEY: en producción no se permite el valor de ejemplo
# (de lo contrario un atacante podría forjar tokens válidos).
if not DEBUG and SECRET_KEY in ('', 'change-this-in-production-use-env-file'):
    raise RuntimeError(
        'SECRET_KEY inseguro o ausente. Define una SECRET_KEY fuerte por variable de '
        'entorno antes de ejecutar en producción.'
    )

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    # Local apps
    'api',
    'inventory',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS debe estar antes de CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.ErrorHandlingMiddleware',  # Error handling global
    # Publica el usuario autenticado para el trigger de auditoría de productos.
    # Va al final para que la sesión de Django ya esté resuelta.
    'api.middleware.AuditoriaUsuarioMiddleware',
]

ROOT_URLCONF = 'inventrix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventrix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Usar DATABASE_URL o db_uri del .env
DATABASE_URL = os.getenv('DATABASE_URL') or os.getenv('db_uri')

if DATABASE_URL:
    # Si existe una URI de base de datos, usarla
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Fallback a configuración individual
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'inventrix'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Cache
# https://docs.djangoproject.com/en/5.2/topics/cache/
# Usa Redis si REDIS_URL está definido; en su defecto cae a memoria local
# (por proceso). El cache acelera los reportes pesados vía cache_page.
REDIS_URL = os.getenv('REDIS_URL')

# En producción con múltiples workers de Gunicorn, LocMemCache no se comparte
# entre procesos y produce cache inconsistente. Redis es obligatorio ahí.
if not DEBUG and not REDIS_URL:
    raise RuntimeError(
        'REDIS_URL no definido. En producción Redis es obligatorio: sin él, '
        'cada worker de Gunicorn tiene su propia caché en memoria '
        '(datos inconsistentes entre requests).'
    )

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,  # si Redis cae, no romper la app
            },
            'KEY_PREFIX': 'inventrix',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    # Autenticación JWT — toda la API exige usuario autenticado
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Rate limiting (anti fuerza bruta en login + límite general)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        # Reducido de 1000 a 500/min (US-11): sigue holgado para las ráfagas
        # del dashboard (varias insights en paralelo) pero acota abuso.
        'user': '500/min',
        'login': '5/min',
    },
}

from datetime import timedelta  # noqa: E402
SIMPLE_JWT = {
    # Reducido de 60 a 30 min (US-11): el refresh es transparente (rotación +
    # reintento automático en el interceptor del frontend), así que acortar la
    # vida del access token limita la ventana de un token robado sin molestar.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
).split(',')

# Falso (US-11): la autenticación va por header Authorization (JWT), no por
# cookies cross-origin, así que no hace falta permitir credenciales.
CORS_ALLOW_CREDENTIALS = False

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'error.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'api_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'api.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'api_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'inventory': {
            'handlers': ['console', 'api_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Crear directorio de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    LOGS_DIR.mkdir(parents=True, exist_ok=True)

# Custom Exception Handler para DRF
REST_FRAMEWORK['EXCEPTION_HANDLER'] = 'api.exception_handler.custom_exception_handler'

# Cloudflare R2 Configuration
R2_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID')
R2_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY')
R2_BUCKET_NAME = os.getenv('R2_BUCKET_NAME')
R2_PUBLIC_URL = os.getenv('R2_PUBLIC_URL')
R2_ACCESS_URI = os.getenv('R2_ACCESS_URI')

# Bucket PRIVADO para los respaldos de la base. Va aparte de R2_BUCKET_NAME a
# propósito: ese tiene un dominio público (sirve las fotos de la bitácora) y
# cualquier respaldo ahí queda descargable sin autenticación. Sin esta variable
# el respaldo no sale del servidor.
R2_BACKUP_BUCKET = os.getenv('R2_BACKUP_BUCKET')

# Cifra el volcado antes de subirlo. Es independiente de FIELD_ENCRYPTION_KEY
# para que una filtración de respaldos no comprometa también los datos de
# contacto cifrados en la base (ni al revés).
BACKUP_ENCRYPTION_KEY = os.getenv('BACKUP_ENCRYPTION_KEY', '')

# Pronóstico de demanda: parámetros del cálculo de recompra.
#
# Plazo de entrega por defecto, en días, cuando un proveedor no tiene el suyo
# cargado ni recepciones medidas. 15 días es un supuesto conservador para
# Nicaragua contemplando proveedores locales e importadores; el reporte declara
# cuándo usó este valor en vez de un dato real, para no confundirlos.
PRONOSTICO_PLAZO_DEFAULT_DIAS = int(os.getenv('PRONOSTICO_PLAZO_DEFAULT_DIAS') or 15)

# Días extra de inventario sobre el plazo de entrega, para absorber que la
# demanda no llega parejo. Con 2-3 ventas al mes por producto la desviación
# estándar es ruido, así que se usa un margen en días en vez de una fórmula
# estadística que daría una precisión falsa.
PRONOSTICO_COLCHON_DIAS = int(os.getenv('PRONOSTICO_COLCHON_DIAS') or 7)

# Clave de cifrado en reposo (R06) para columnas de contacto sensibles
# (telefono/email de clientes y proveedores). Ver inventory/encryption.py.
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY', '')
if not DEBUG and not FIELD_ENCRYPTION_KEY:
    raise RuntimeError(
        'FIELD_ENCRYPTION_KEY no definido. Es obligatorio en producción para '
        'cifrar telefono/email de clientes y proveedores. Generar uno con: '
        'python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"'
    )

# En producción, si se define alguna credencial de R2 deben definirse todas
# (fail-fast en vez de fallar silenciosamente al subir la primera foto).
_R2_VARS = {
    'R2_ACCESS_KEY_ID': R2_ACCESS_KEY_ID,
    'R2_SECRET_ACCESS_KEY': R2_SECRET_ACCESS_KEY,
    'R2_BUCKET_NAME': R2_BUCKET_NAME,
    'R2_PUBLIC_URL': R2_PUBLIC_URL,
    'R2_ACCESS_URI': R2_ACCESS_URI,
}
if not DEBUG and any(_R2_VARS.values()) and not all(_R2_VARS.values()):
    _faltantes = [k for k, v in _R2_VARS.items() if not v]
    raise RuntimeError(
        f'Configuración de Cloudflare R2 incompleta. Faltan: {", ".join(_faltantes)}. '
        'Define todas las variables R2_* o ninguna.'
    )

# ============================================================================
# Seguridad de producción (US-06)
# ============================================================================
# Solo se activan con DEBUG=False para no romper el desarrollo local por HTTP.
if not DEBUG:
    # Detrás del proxy de Dokploy (Traefik): confiar en el header para que
    # request.is_secure() detecte bien HTTPS (usado por las cookies Secure).
    #
    # SECURE_SSL_REDIRECT queda deliberadamente en False (default): Traefik ya
    # fuerza HTTPS en el borde y agrega/reescribe X-Forwarded-Proto de forma
    # que Django no puede confiar en detectar "ya es HTTPS" de forma fiable.
    # Con SECURE_SSL_REDIRECT=True, cualquier request que Django considere NO
    # segura recibe 301 — incluyendo los preflight OPTIONS de CORS, que el
    # navegador no puede seguir, rompiendo login y toda la API (visto en
    # producción: "OPTIONS /api/... 301" en todos los endpoints).
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Cookies solo por HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS: fuerza HTTPS en el navegador durante 1 año.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Evita que el navegador "adivine" el content-type (anti MIME sniffing).
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Orígenes de confianza para CSRF (panel admin de Django): dominios reales
    # en https, derivados de ALLOWED_HOSTS + orígenes CORS. Se excluye
    # localhost y cualquier entrada mal formada (URLs dentro de ALLOWED_HOSTS).
    _csrf_origins = {o for o in CORS_ALLOWED_ORIGINS if o.startswith('https://')}
    for _host in ALLOWED_HOSTS:
        _host = _host.strip()
        if _host and _host not in ('localhost', '127.0.0.1') and not _host.startswith('http'):
            _csrf_origins.add(f'https://{_host}')
    CSRF_TRUSTED_ORIGINS = sorted(_csrf_origins)

