# Generated by Django 4.2.7 on 2025-11-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_cliente_activo_remove_producto_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
