# Generated by Django 4.2.7 on 2025-11-08 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='detalleordencompra',
            options={'managed': False, 'verbose_name': 'Detalle de Orden de Compra', 'verbose_name_plural': 'Detalles de Órdenes de Compra'},
        ),
        migrations.AlterModelOptions(
            name='detalleordenventa',
            options={'managed': False, 'verbose_name': 'Detalle de Orden de Venta', 'verbose_name_plural': 'Detalles de Órdenes de Venta'},
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'managed': False, 'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'managed': False, 'ordering': ['-fecha_creacion'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterModelOptions(
            name='ordenventa',
            options={'managed': False, 'ordering': ['-fecha_creacion'], 'verbose_name': 'Orden de Venta', 'verbose_name_plural': 'Órdenes de Venta'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
