# Generated by Django 5.2 on 2026-07-24 23:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_gastos'),
    ]

    operations = [
        # orden_producto no tiene modelo Django (se maneja por SQL crudo en los
        # serializers). Agregamos cantidad + precio_unitario para poder guardar
        # el detalle real de la compra y calcular su total correctamente.
        # Las filas históricas quedan en NULL (el dato nunca se capturó).
        migrations.RunSQL(
            sql="""
                ALTER TABLE orden_producto
                    ADD COLUMN IF NOT EXISTS cantidad INTEGER,
                    ADD COLUMN IF NOT EXISTS precio_unitario NUMERIC(10,2);
            """,
            reverse_sql="""
                ALTER TABLE orden_producto
                    DROP COLUMN IF EXISTS cantidad,
                    DROP COLUMN IF EXISTS precio_unitario;
            """,
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('deposito', 'Depósito'), ('cheque', 'Cheque')], default='efectivo', max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventory.ordencompra')),
                ('sesion', models.ForeignKey(blank=True, db_column='id_sesion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_compra', to='inventory.sesioncaja')),
            ],
            options={
                'verbose_name': 'Pago de Compra',
                'verbose_name_plural': 'Pagos de Compras',
                'db_table': 'pago_compra',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
    ]
