# Generated by Django 5.2 on 2026-07-25 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def sembrar_catalogo(apps, schema_editor):
    """Deriva el catálogo de tipos de servicio del histórico de `servicios`.

    Las filas históricas (una por trabajo realizado, con su moto y fecha) no se
    tocan: hay 98 ventas apuntando a ellas. Se agregan filas nuevas marcadas
    como plantilla, deduplicadas por (nombre, tipo).
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT nombre, tipo, MIN(precio_mano_obra)
            FROM servicios
            WHERE es_plantilla = FALSE
            GROUP BY nombre, tipo
            ORDER BY nombre
        """)
        tipos = cursor.fetchall()

        for nombre, tipo, precio in tipos:
            # Idempotente: si ya existe la plantilla no se duplica.
            cursor.execute(
                "SELECT 1 FROM servicios WHERE es_plantilla = TRUE AND nombre = %s AND tipo = %s",
                [nombre, tipo],
            )
            if cursor.fetchone():
                continue
            cursor.execute("""
                INSERT INTO servicios (nombre, tipo, precio_mano_obra, es_plantilla)
                VALUES (%s, %s, %s, TRUE)
            """, [nombre, tipo, precio])


def revertir_catalogo(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DELETE FROM servicios WHERE es_plantilla = TRUE")


def normalizar_ordenes_historicas(apps, schema_editor):
    """Las órdenes que ya existían son trabajo terminado, no citas pendientes.

    `estado` entra con default 'agendada', que sería falso para ellas. También
    se copia `costo` a `precio_mano_obra` para que calcular_total() (mano de
    obra + repuestos) no las deje en cero: no tienen repuestos registrados.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE servicio_motos
            SET estado = 'entregada',
                precio_mano_obra = COALESCE(costo, 0)
            WHERE estado = 'agendada'
        """)


def backfill_venta(apps, schema_editor):
    """Guarda explícitamente el vínculo servicio↔venta que hoy se adivina.

    Hasta ahora la venta que generaba un servicio no quedaba referenciada en
    ningún lado y se reconstruía cruzando fecha + costo + cliente. Se hace ese
    cruce UNA última vez y se persiste el resultado, garantizando 1:1 (una venta
    no puede quedar asignada a dos servicios). Los servicios sin coincidencia
    quedan en NULL a propósito: no hay forma confiable de saber a qué venta
    corresponden.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT sm.id_servicio, v.id_venta
            FROM servicio_motos sm
            JOIN motos m ON m.id_moto = sm.id_moto
            JOIN ventas v ON v.fecha = sm.fecha_servicio
                         AND v.total = sm.costo
                         AND v.id_cliente = m.id_cliente
            WHERE sm.id_venta IS NULL
            ORDER BY sm.id_servicio, v.id_venta
        """)

        ventas_usadas = set()
        servicios_resueltos = set()
        for id_servicio, id_venta in cursor.fetchall():
            if id_venta in ventas_usadas or id_servicio in servicios_resueltos:
                continue
            ventas_usadas.add(id_venta)
            servicios_resueltos.add(id_servicio)
            cursor.execute(
                "UPDATE servicio_motos SET id_venta = %s WHERE id_servicio = %s",
                [id_venta, id_servicio],
            )


def revertir_backfill(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("UPDATE servicio_motos SET id_venta = NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_cuentas_por_pagar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='es_plantilla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='estado',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('recibida', 'Recibida'), ('en_diagnostico', 'En diagnóstico'), ('en_reparacion', 'En reparación'), ('esperando_repuesto', 'Esperando repuesto'), ('lista', 'Lista para entrega'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='agendada', max_length=30),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='fecha_cita',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='id_mecanico',
            field=models.ForeignKey(blank=True, db_column='id_mecanico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='id_tipo_servicio',
            field=models.ForeignKey(blank=True, db_column='id_tipo_servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='inventory.servicio'),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_taller', to='inventory.ordenventa'),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='km_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='precio_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='proximo_mantenimiento_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='proximo_mantenimiento_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_referencia',
            field=models.CharField(blank=True, choices=[('ORDEN_COMPRA', 'Orden de Compra'), ('ORDEN_VENTA', 'Orden de Venta'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('SERVICIO_TALLER', 'Servicio de Taller')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ServicioRepuesto',
            fields=[
                ('id_servicio_repuesto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_taller', to='inventory.producto')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='inventory.serviciomoto')),
            ],
            options={
                'verbose_name': 'Repuesto de Servicio',
                'verbose_name_plural': 'Repuestos de Servicios',
                'db_table': 'servicio_repuesto',
                'ordering': ['id_servicio_repuesto'],
            },
        ),
        # El esquema real trae un CHECK que limita tipo_referencia a los tres
        # valores originales, así que el nuevo choice SÍ necesita DDL: sin esto,
        # registrar el consumo de un repuesto viola el constraint.
        migrations.RunSQL(
            sql="""
                ALTER TABLE movimientos_inventario
                    DROP CONSTRAINT IF EXISTS movimientos_inventario_tipo_referencia_check;
                ALTER TABLE movimientos_inventario
                    ADD CONSTRAINT movimientos_inventario_tipo_referencia_check
                    CHECK (tipo_referencia IS NULL OR tipo_referencia IN (
                        'ORDEN_COMPRA', 'ORDEN_VENTA', 'AJUSTE_MANUAL', 'SERVICIO_TALLER'
                    ));
            """,
            reverse_sql="""
                ALTER TABLE movimientos_inventario
                    DROP CONSTRAINT IF EXISTS movimientos_inventario_tipo_referencia_check;
                ALTER TABLE movimientos_inventario
                    ADD CONSTRAINT movimientos_inventario_tipo_referencia_check
                    CHECK (tipo_referencia IS NULL OR tipo_referencia IN (
                        'ORDEN_COMPRA', 'ORDEN_VENTA', 'AJUSTE_MANUAL'
                    ));
            """,
        ),
        migrations.RunPython(sembrar_catalogo, revertir_catalogo),
        migrations.RunPython(normalizar_ordenes_historicas, migrations.RunPython.noop),
        migrations.RunPython(backfill_venta, revertir_backfill),
    ]
