# Generated by Django 5.2 on 2026-07-26 00:26

import django.db.models.deletion
from django.db import migrations, models


def sanear_saldos_nulos(apps, schema_editor):
    """Hace visibles las deudas que el reporte de Cuentas por Cobrar no mostraba.

    `cuentas_por_cobrar` filtra por `COALESCE(saldo_pendiente, 0) > 0`, así que
    una venta con `estado_pago='pendiente'` y `saldo_pendiente = NULL` quedaba
    fuera del reporte: la deuda existía pero era invisible. La columna es
    nullable sin default y varios INSERT crudos la omitían.

    El recálculo es determinista (saldo = total - pagado), no se adivina nada.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE ventas
            SET saldo_pendiente = COALESCE(total, 0) - COALESCE(monto_pagado, 0)
            WHERE saldo_pendiente IS NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_agenda_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='aprobado_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cargado_a_orden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='id_moto',
            field=models.ForeignKey(blank=True, db_column='id_moto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='inventory.moto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='id_servicio',
            field=models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='inventory.serviciomoto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Proforma de productos'), ('reparacion', 'Presupuesto de reparación')], default='producto', max_length=20),
        ),
        migrations.CreateModel(
            name='ServicioCotizacion',
            fields=[
                ('id_servicio_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cotizacion', models.ForeignKey(db_column='id_cotizacion', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='inventory.cotizacion')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='lineas_presupuesto', to='inventory.servicio')),
            ],
            options={
                'verbose_name': 'Mano de obra presupuestada',
                'verbose_name_plural': 'Mano de obra presupuestada',
                'db_table': 'servicio_cotizacion',
                'ordering': ['id_servicio_cotizacion'],
            },
        ),
        # Reversa noop: volver los saldos a NULL sería reintroducir el bug.
        migrations.RunPython(sanear_saldos_nulos, migrations.RunPython.noop),
    ]
