# Generated by Django 5.2 on 2026-07-26 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_presupuestos_reparacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('bodega', models.CharField(default='Principal', max_length=100)),
                ('pasillo', models.CharField(blank=True, max_length=50, null=True)),
                ('estante', models.CharField(blank=True, max_length=50, null=True)),
                ('gaveta', models.CharField(blank=True, max_length=50, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
                'ordering': ['bodega', 'pasillo', 'estante', 'gaveta'],
                'constraints': [models.UniqueConstraint(fields=('bodega', 'pasillo', 'estante', 'gaveta'), name='ubicacion_unica', nulls_distinct=False)],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_ubicacion',
            field=models.ForeignKey(blank=True, db_column='id_ubicacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventory.ubicacion'),
        ),
    ]
