# Generated by Django 5.2 on 2026-07-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_ubicacion_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='stock_aplicado',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
