# Generated by Django 5.2 on 2026-07-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_recepcion_suma_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_esperada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
