# Generated by Django 5.2 on 2026-07-26 04:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_desempeno_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionCompra',
            fields=[
                ('id_devolucion_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reembolso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_reembolso', models.CharField(choices=[('credito', 'Nota de crédito'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('deposito', 'Depósito'), ('cheque', 'Cheque')], default='credito', max_length=20)),
                ('creado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='inventory.ordencompra')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_recibidas', to='inventory.proveedor')),
                ('sesion', models.ForeignKey(blank=True, db_column='id_sesion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='inventory.sesioncaja')),
            ],
            options={
                'verbose_name': 'Devolución a proveedor',
                'verbose_name_plural': 'Devoluciones a proveedores',
                'db_table': 'devolucion_compra',
                'ordering': ['-fecha', '-id_devolucion_compra'],
            },
        ),
        migrations.CreateModel(
            name='ProductoDevolucionCompra',
            fields=[
                ('id_producto_devolucion_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_devolucion_compra', models.ForeignKey(db_column='id_devolucion_compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.devolucioncompra')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_a_proveedor', to='inventory.producto')),
            ],
            options={
                'verbose_name': 'Línea de devolución a proveedor',
                'verbose_name_plural': 'Líneas de devolución a proveedor',
                'db_table': 'producto_devolucion_compra',
                'ordering': ['id_producto_devolucion_compra'],
            },
        ),
    ]
