# Generated by Django 5.2 on 2026-07-26 16:38

import inventory.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auditoria_usuario_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIA',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=30, unique=True)),
                ('api_key', inventory.encryption.EncryptedCharField(blank=True, max_length=500, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('verificada', models.BooleanField(default=False)),
                ('verificada_en', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración de IA',
                'verbose_name_plural': 'Configuración de IA',
                'db_table': 'configuracion_ia',
                'ordering': ['proveedor'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='un_solo_proveedor_ia_activo')],
            },
        ),
    ]
