# Generated by Django 5.2 on 2026-07-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_configuracion_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='dias_entrega_estimado',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Días que suele tardar en entregar. Vacío = se usa el valor por defecto del sistema.', null=True),
        ),
    ]
